FROM golang:1 As builder
WORKDIR /app
ADD ./golang ./
RUN go build -o app
FROM ubuntu:20.04
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install curl -y && \
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/app /app
RUN mkdir tmp
CMD ["./app"]