apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-rc.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: kube-state-metrics
  ports:
    - name: http-metrics
      port: 8080
      # targetPort: 8080
      nodePort: 30003
    - name: telemetry
      port: 8081
      # targetPort: 8080
      nodePort: 30004
  type: LoadBalancer