apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: nextcloud
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  # type: LoadBalancer
  clusterIP: None