apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: gf-space
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        podinfo: "jaeger"
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.57
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Asia/Tokyo'
            - name: SPAN_STORAGE_TYPE
              value: badger
            - name: BADGER_EPHEMERAL
              value: "false"
            - name: BADGER_DIRECTORY_VALUE
              value: /badger/data
            - name: BADGER_DIRECTORY_KEY
              value: /badger/key
          ports:
            - name: query
              containerPort: 16686
            - name: collector-grpc
              containerPort: 4317
            - name: collector-http
              containerPort: 4318
          resources:
            requests:
              cpu: "500m"
              memory: 512Mi
          volumeMounts:
            - name: jaeger-vol
              mountPath: /badger
      volumes:
        - name: jaeger-vol
          persistentVolumeClaim:
            claimName: jaeger-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: gf-space
spec:
  selector:
    app: jaeger
  ports:
    - name: http
      port: 16686
      targetPort: 16686
    - name: collector-grpc
      port: 4317
      targetPort: 4317
    - name: collector-http
      port: 4318
      targetPort: 4318
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: gf-space
spec:
  ingressClassName: nginx
  rules:
  - host: jaeger.bookserver.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-service
            port:
              number: 16686
  - host: jaeger-http.bookserver.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-service
            port:
              number: 4318
  - host: jaeger-grpc.bookserver.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-service
            port:
              number: 4317