apiVersion: v1
kind: PersistentVolume
metadata:
  name: "grafana-pv-volume"
  namespace: gf-space
  labels:
    type: "local"
spec:
  storageClassName: "grafana"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
#   hostPath:
#     path: /home/pi/usb/usb1/grafana
  nfs:
    server: 192.168.0.25
    path: /home/pi/usb/usb1/nfs/grafana-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: gf-space
spec:
  storageClassName: grafana
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
