apiVersion: v1
kind: PersistentVolume
metadata:
  name: "prometheus-pv-volume"
  namespace: gf-space
  labels:
    type: "local"
spec:
  storageClassName: "prometheus"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/nfs/prometheus/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: gf-space
spec:
  storageClassName: prometheus
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
