apiVersion: v1
kind: PersistentVolume
metadata:
  name: "defult-mariadb-pv-volume"
  labels:
    type: "local"
spec:
  storageClassName: "d-mariadb"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/usb/usb1/defult/mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: d-mariadb
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
      annotations:
        podinfo: "default用のMariadbのPod"
    spec:
      containers:
      # - image: turgon37/armhf-mariadb
      - image: mariadb:10.11.4
        imagePullPolicy: IfNotPresent
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_PASSWORD
          value: ampache
        - name: MYSQL_DATABASE
          value: ampache
        - name: MYSQL_USER
          value: ampache
        ports:
        - containerPort: 3306
          name: mariadb
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 1Gi
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      nodeSelector:
        type: k8s-worker-2
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  # type: ClusterIP
  clusterIP: None