# FROM multiarch/ubuntu-core:armhf-bionic As builder
FROM scaleway/ubuntu-coreos As builder
# FROM ubuntu:22.04 As builder
#RUN apt update && apt upgrade -y
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y curl gcc git locales locales-all &&\
    locale-gen ja_JP.UTF-8
RUN curl -OL https://dl.google.com/go/go1.18.2.linux-armv6l.tar.gz &&\
    tar -C /usr/local -xzf go1.18.2.linux-armv6l.tar.gz &&\
    rm -rf go1.18.2.linux-armv6l.tar.gz
ENV PATH $PATH:/usr/local/go/bin
# RUN go get -u github.com/seihmd/openbd &&\
#     go get -u github.com/PuerkitoBio/goquery &&\
#     go get -u github.com/go-sql-driver/mysql &&\
#     go get -u github.com/mattn/go-sqlite3
WORKDIR /app
ADD ./golang .
RUN go build -o app
# FROM multiarch/ubuntu-core:armhf-bionic
FROM scaleway/ubuntu-coreos
# FROM ubuntu:22.04
LABEL maintainer "karosu <karosuwindam@gmail.com>"
LABEL version="0.12.0"
LABEL docker_arch="arm"
LABEL go_version="1.18.2"
LABEL name="booknewread"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl && \
#    locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ./golang-v2/bookmarks.html ./
COPY ./golang-v2/html html
COPY ./golang-v2/bookmark bookmark
COPY ./golang-v2/run.sh ./
COPY --from=builder /app/app /app
RUN chmod +x run.sh
# COPY ./app /app
CMD ["./run.sh"]
