FROM multiarch/ubuntu-core:armhf-bionic As builder
#RUN apt update && apt upgrade -y
RUN apt update && apt upgrade -y && \
    apt install -y curl gcc git locales locales-all &&\
    locale-gen ja_JP.UTF-8
RUN curl -OL https://dl.google.com/go/go1.16.5.linux-armv6l.tar.gz &&\
    tar -C /usr/local -xzf go1.16.5.linux-armv6l.tar.gz &&\
    rm -rf go1.16.5.linux-armv6l.tar.gz
ENV PATH $PATH:/usr/local/go/bin
RUN go get -u github.com/seihmd/openbd &&\
    go get -u github.com/PuerkitoBio/goquery &&\
    go get -u github.com/go-sql-driver/mysql &&\
    go get -u github.com/mattn/go-sqlite3
WORKDIR /app
ADD ./golang .
RUN go build -o app
FROM multiarch/ubuntu-core:armhf-bionic
# FROM ubuntu:20.04
LABEL maintainer "karosu <karosuwindam@gmail.com>"
LABEL version="0.8.4"
LABEL name="booknewread"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl && \
#    locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ./golang/config config
COPY ./golang/html html
COPY ./golang/bookmark bookmark
COPY ./golang/bookmarks.html ./
COPY ./golang/run.sh ./
COPY --from=builder /app/app /app
# COPY ./app /app
CMD ["./run.sh"]
