apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: nextcloud
spec:
  ingressClassName: nginx
  rules:
  - host: nextcloud.bookserver.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nextcloud-service
            port: 
              number: 80
