apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gogpio
spec:
  selector:
    matchLabels:
      name: gogpio
  template:
    metadata:
      labels:
        name: gogpio
    #   annotations:
    #     prometheus.io/scrape: 'true'
    #     prometheus.io/port: '9100'
    #     prometheus.io/path: /metrics
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm
                - key: gpio
                  operator: In
                  values:
                    - "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: gogpio
        image: bookserver2:31000/test/gogpio:runtest3 #prom/node-exporter
        imagePullPolicy: IfNotPresent
        env:
          - name: WEB_PORT
            value: "9999"
        ports:
          - containerPort: 9999
        # hostDevices:
        #   - /dev/gpiomem
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
   