apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com
  versions:
  # - name: v1beta1
  #   served: true
  #   storage: true
  #   schema:
  #     openAPIV3Schema:
  #       type: object
  #       properties:
  #         host:
  #           type: string
  #         port:
  #           type: string
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          host:
            type: string
          port:
            type: string
          image:
            type: string
          spec:
            type: object
            properties:
              cronSpec:
                type: string
              message:
                type: string
            required:
            - cronSpec
        #     - message
  scope: Namespaced
  names:
    plural: samples
    singular: sample
    kind: Sample
    shortNames:
    - sp