apiVersion: v1
kind: PersistentVolume
metadata:
  name: "gogpio-pv-volume"
  labels:
    type: "local"
spec:
  storageClassName: "gogpio"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/nfs/prometheus/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogpio-pv-claim
spec:
  storageClassName: gogpio
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
