apiVersion: apiextensions.k8s.io/v1beta1
# apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com
  # versions:
  # - name: v1beta
  #   served: true
  #   storage: true
  version: v1beta
  scope: Namespaced
  names:
    kind: Sample
    plural: samples
    singular: sample
    # shortNames: ["sp"]
    shortNames:
        - wf