apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotext-deploy
spec:
  selector:
    matchLabels:
      app: gotext
  replicas: 1
  template:
    metadata:
      labels:
        app: gotext
      annotations:
        podinfo: "年代ごとのアニメタイトル"
    spec:
      containers:
      - name: gotext
        image: bookserver2:31000/tool/gotext-server:0.0.4
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Always
        env:
          - name: TZ
            value: 'Asia/Tokyo'
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /app/txt
            name: gotext-storage
        resources:
          limits:
            cpu: 0.3
            memory: 200Mi
          requests:
            cpu: 0.1
            memory: 100Mi
      volumes:
        - name: gotext-storage
          persistentVolumeClaim:
            claimName: gotext-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gotext-service
spec:
  selector:
    app: gotext
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
