FROM gitpod/openvscode-server:%TAG%
LABEL maintainer "karosu <karosuwindam@gmail.com>"
LABEL version="%TAG%"
LABEL go_version="%GO_VERSION%"
LABEL name="vscode-server"
USER root
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl gcc git locales locales-all make &&\
    locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
RUN curl -OL https://dl.google.com/go/%GO_FILE% &&\
    tar -C /usr/local -xzf %GO_FILE% &&\
    rm -rf %GO_FILE%
USER openvscode-server
ENV PATH $PATH:/usr/local/go/bin