apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booknewread--pv-claim
  namespace: booknew-sp
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi