---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: booknewread-pv-claim
spec:
  storageClassName: booknewread-config
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0004
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booknewread-pvc-claim
  namespace: booknew-sp
spec:
  storageClassName: booknewread-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi