apiVersion: v1
kind: PersistentVolume
metadata:
  name: "koel-pv-volume"
  namespace: koel
  labels:
    type: "local"
spec:
  storageClassName: "koel-mariadb"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/usb/usb1/mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-mariadb
  namespace: koel
spec:
  storageClassName: koel-mariadb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-search-index
  namespace: koel
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-covers
  namespace: koel
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: koel-pv-smb-music
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: koel-smb-music
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: smb-server.default.svc.cluster.local/music##
    volumeAttributes:
      # source: "//smb-server.default.svc.cluster.local/share"
      source: "//192.168.0.6/music"
    nodeStageSecretRef:
      name: smbcreds
      namespace: koel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-music
  namespace: koel
spec:
  storageClassName: koel-smb-music
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---