---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliber-pv-config-web
spec:
  storageClassName: caliber-config-web
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/caliber-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caliber-pvc-config-web
  namespace: caliber
spec:
  storageClassName: caliber-config-web
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliber-pv-library
spec:
  storageClassName: caliber-library
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/caliber-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caliber-pvc-library
  namespace: caliber
spec:
  storageClassName: caliber-library
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi