---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-movies
spec:
  storageClassName: jellyfin-movies
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.0.6
    path: /video/video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-movies
  namespace: jellyfin
spec:
  storageClassName: jellyfin-movies
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi