apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: jellyfin-pv-smb-pi
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jellyfin-smb-pi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: smb-server.default.svc.cluster.local/pi##
    volumeAttributes:
      # source: "//smb-server.default.svc.cluster.local/share"
      source: "//k8s-worker-2.local/pi"
    nodeStageSecretRef:
      name: smbpicreds
      namespace: jellyfin
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-pvc-smb-pi
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: jellyfin-smb-pi