---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0001
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0002
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0003
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0004
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0005
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0006
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0007
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0007
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0008
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0008
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0009
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/pv0009