apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-pv-volume2"
  namespace: nextcloud
  labels:
    type: "local"
spec:
  storageClassName: "mariadb2"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/usb/usb1/mariadb2
  # nfs:
  #   server: 192.168.0.24
  #   path: /home/pi/usb/usb0/mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim2
  namespace: nextcloud
spec:
  storageClassName: mariadb2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi