---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ampache-pvc-config
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ampache-pvc-log
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ampache-pvc-media
# spec:
#   # storageClassName: smb
#   storageClassName: smb-www-data
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ampache-pvc-mysql
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
