apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  selector:
    matchLabels:
      app: nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        # image: arm32v7/nextcloud
        # image: nextcloud_app
        image: bookserver2:31000/karosu/nextcloud_smb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2
            memory: 1.5Gi
          requests:
            cpu: 1
            memory: 400Mi
        volumeMounts:
        - name: nextcloud-st
          mountPath: /var/www/html/
      nodeSelector:
        type: k8s-worker-1
      volumes:
      - name: nextcloud-st
        persistentVolumeClaim:
          claimName: nextcloud-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

