apiVersion: v1
kind: Service
metadata:
  name: promtail-pod
  namespace: gf-space
spec:
  selector:
    name: promtail-pod
    # name: promtail
  ports:
    - port: 9080
      targetPort: 9080
      # nodePort: 30748
  # type: LoadBalancer
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promtail-pod-ingress
  namespace: gf-space
spec:
  ingressClassName: nginx
  rules:
  - host: promtail.bookserver.home
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: promtail-pod
            port: 
              number: 9080
