apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud.ini
  namespace: nextcloud
data:
  nextcloud.ini: |
    memory_limit=${PHP_MEMORY_LIMIT}
    upload_max_filesize=${PHP_UPLOAD_LIMIT}
    post_max_size=${PHP_UPLOAD_LIMIT}
    max_execution_time=1800
    max_input_time=1800

