apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  server.conf: |
    server{
        server_name    bookserver2.local;
        listen 443 ssl;
        # 自己署名証明書
        ssl_certificate /etc/nginx/ssl/nginx.pem;
        # 暗号化鍵
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        proxy_set_header    Host    $host;
        proxy_set_header    X-Real-IP    $remote_addr;
        proxy_set_header    X-Forwarded-Host       $host;
        proxy_set_header    X-Forwarded-Server    $host;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
        dav_methods  PUT;
        location / {
            proxy_pass    http://localhost:4000/;
            client_max_body_size 500M;
        }
        location /cp/{
        proxy_pass     http://localhost:5100/;
            client_max_body_size 100M;
        }
    }