apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: isbn-sp-ingress
  namespace: isbn-sp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - backend:
          serviceName: isbn-service
          servicePort: 8080
    # https:
    #   paths:
    #   - backend:
    #       serviceName: isbn-service
    #       servicePort: 8080