---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pv-claim
  namespace: gf-space
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi