FROM multiarch/ubuntu-core:armhf-bionic As builder
#RUN apt update && apt upgrade -y
RUN apt update && apt upgrade -y && \
    apt install -y curl gcc git locales locales-all &&\
    locale-gen ja_JP.UTF-8
RUN curl -OL https://dl.google.com/go/go1.18.1.linux-armv6l.tar.gz &&\
    tar -C /usr/local -xzf go1.18.1.linux-armv6l.tar.gz &&\
    rm -rf go1.18.1.linux-armv6l.tar.gz
ENV PATH $PATH:/usr/local/go/bin
# RUN go get -u k8s.io/apimachinery/pkg/apis/meta/v1 &&\
#     go get -u k8s.io/client-go/...
WORKDIR /app
ADD ./golang .
RUN go build -o app
FROM multiarch/ubuntu-core:armhf-bionic
# FROM ubuntu:20.04
LABEL maintainer "karosu <karosuwindam@gmail.com>"
LABEL version="0.3.0"
LABEL name="client-go"
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y locales locales-all curl && \
#    locale-gen ja_JP.UTF-8 &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ./golang/config config
COPY ./golang/html html
# COPY ./golang/bookmark bookmark
COPY --from=builder /app/app /app
# COPY ./app /app
CMD ["./app"]
