---
apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-env
data:
  ND_SCANSCHEDULE: 1h
  ND_LOGLEVEL: info  
  ND_SESSIONTIMEOUT: 24h
  ND_BASEURL: ""
  TZ: "Asia/Tokyo"
  # TZ: "Europe/London"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
      annotations:
        podinfo: "navidrome:音楽再生の総合管理"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: navidrome
          image: deluan/navidrome:0.49.3
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: navidrome-env
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-pvc-data 
        - name: music
          persistentVolumeClaim:
            claimName: navidrome-pvc-music 
---