---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-pv-manga
spec:
  storageClassName: kavita-manga
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.0.6
    path: /Booknew/scan_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-pvc-manga
  namespace: kavita
spec:
  storageClassName: kavita-manga
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi