apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-config
spec:
  storageClassName: kavita-config
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kavita-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-pvc-config
  namespace: kavita
spec:
  storageClassName: kavita-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
