
apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer
  annotations:
    volume.beta.kubernetes.io/storage-class: "generic"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/portainer