apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: gf-space
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9080'
        prometheus.io/path: /metrics
        podinfo: "各ノード内のPodや本体のデータ監視用のpromtail"
    spec:
      serviceAccountName: promtail
      serviceAccount: promtail
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
      - name: promtail
        image: grafana/promtail:2.8.11
        # image: grafana/promtail:2.7.4
        # image: grafana/promtail
        args:
        - --config.file=/etc/promtail/config.yaml
        - --config.expand-env=true
        # - --config.expand-env=true
        # - --config.file=/etc/promtail/config.yml
        env: 
        - name: 'HOSTNAME' # needed when using kubernetes_sd_configs
          valueFrom:
            fieldRef:
              fieldPath: 'spec.nodeName'
        ports:
        - containerPort: 9080
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 300Mi
        volumeMounts:
        - name: log
          mountPath: /var/log
        - name: journal-var
          mountPath: /var/log/journal
          readOnly: true
        - name: journal-run
          mountPath: /run/log/journal
          readOnly: true
        #   readOnly: true
    #     - name: run
    #       mountPath: /var/run
    #     - name: sys
    #       mountPath: /sys
    #       readOnly: true
    #     - name: docker
    #       mountPath: /var/lib/docker
    #       readOnly: true
    #     - name: disk
    #       mountPath: /dev/disk
    #       readOnly: true
        - name: config-vol
          mountPath: /etc/promtail/config.yaml
          subPath: config.yaml
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
    #   terminationGracePeriodSeconds: 30
    #   hostNetwork: true
    #   hostPID: true
      volumes:
      - name: log
        hostPath:
          path: /var/log
    #   - name: run
    #     hostPath:
    #       path: /var/run
    #   - name: sys
    #     hostPath:
    #       path: /sys
    #   - name: docker
    #     hostPath:
    #       path: /var/lib/docker
    #   - name: disk
    #     hostPath:
    #       path: /dev/disk
      - hostPath:
          path: /var/log/journal
        name: journal-var
      - hostPath:
          path: /run/log/journal
        name: journal-run
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-vol
        configMap:
          name: promtail-configmap
          items:
            - key: config.yaml
              path: config.yaml