---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-config
spec:
  storageClassName: jellyfin-config
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: k8s-worker-3
    # path: /home/pi/usb/usb1/nfs/kubernetes/jellyfin-config
    path: /home/pi/usb/usb1/nfs/jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-config
  namespace: jellyfin
spec:
  storageClassName: jellyfin-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-movies
spec:
  storageClassName: jellyfin-movies
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.0.6
    path: /video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-movies
  namespace: jellyfin
spec:
  storageClassName: jellyfin-movies
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi