apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-go
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: client-go
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: client-go
subjects:
  - kind: ServiceAccount
    name: client-go