apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: booknewread-ingress
  namespace: booknew-sp
  # Label:
  #   title-name: "本や図書の新刊リストや読み物サイト更新"
spec:
  rules:
  - host: booknewread.bookserver.local
    http:
      paths:
      - backend:
          serviceName: booknewread-service
          servicePort: 8080
  - host: booknewread.bookserver.home
    http:
      paths:
      - backend:
          serviceName: booknewread-service
          servicePort: 8080