apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booknewread-ingress
  namespace: booknew-sp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  # Label:
  #   title-name: "本や図書の新刊リストや読み物サイト更新"
spec:
  ingressClassName: nginx
  rules:
  - host: booknewread.bookserver.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: booknewread-service
            port:
              number: 8080
  - host: booknewread.bookserver.home
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: booknewread-service
            port:
              number: 8080