apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: booknewread-ingress
  namespace: booknew-sp
spec:
  rules:
  - host: booknewread.bookserver.local
    http:
      paths:
      - backend:
          serviceName: booknewread-service
          servicePort: 8080