---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-mariadb
  namespace: koel
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-search-index
  namespace: koel
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-covers
  namespace: koel
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-pvc-music
  namespace: koel
spec:
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---