apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-sample-pvc-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi