apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockeri2cmoni-i2c
  namespace: gf-space
spec:
  selector:
    matchLabels:
      name: dockeri2cmoni
  template:
    metadata:
      labels:
        name: dockeri2cmoni
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9140'
        prometheus.io/path: /metrics
        podinfo: "Raspberrypi用 Prometeusエージェント"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm
                - key: i2c
                  operator: In
                  values:
                    - "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: dockeri2cmoni
        image: bookserver2:31000/moni/dockeri2cmoni:0.83
        ports:
        - containerPort: 9140
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
