apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: exporter
  namespace: gf-space
spec:
  selector:
    matchLabels:
      name: exporter
  template:
    metadata:
      labels:
        name: exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
        prometheus.io/path: /metrics
        podinfo: "Exporter Prometeusエージェント"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm
                    - arm64
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: exporter
        image: prom/node-exporter:v1.6.0
        # image: prom/node-exporter:v1.3.1
        # image: prom/node-exporter:v1.5.0
        ports:
        - containerPort: 9100
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: usb1
          mountPath: /home/pi/usb/usb1
        - name: usb2
          mountPath: /home/pi/usb/usb2
          readOnly: true
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
      volumes:
      - name: usb1
        hostPath:
          path: /home/pi/usb/usb1
      - name: usb2
        hostPath:
          path: /home/pi/usb/usb2
