apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: gf-space
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          # image: grafana/grafana:7.4.3
          image: grafana/grafana:8.2.3
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Asia/Tokyo'
            # - name: GF_INSTALL_PLUGINS
            #   value: 'grafana-image-renderer'
              # value: 'nec-baas-iframe-panel'
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-vol
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-vol
              mountPath: /var/lib/grafana
    #   nodeSelector:
    #     type: k8s-worker-1
      volumes:
        - name: grafana-vol
          persistentVolumeClaim:
            claimName: grafana-pv-claim
        - name: config-vol
          configMap:
            name: grafana-configmap
            items:
              - key: defaults.ini
                path: grafana.ini
---
