apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus2
  namespace: gf-space
spec:
  selector:
    matchLabels:
      app: prometheus2
  template:
    metadata:
      labels:
        app: prometheus2
      annotations:
        podinfo: "Prometheus データ収集用"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "raspberrypi5"
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers:
        - name: prometheus2
          # image: prom/prometheus:v2.24.1
          # image: prom/prometheus:v2.35.0
          image: prom/prometheus:v2.43.0
          imagePullPolicy: IfNotPresent
          #/bin/prometheus
          #-config.file=/etc/prometheus/prometheus.yml
          #-storage.tsdb.path=/prometheus
          #-web.console.libraries=/usr/share/prometheus/console_libraries
          #-web.console.templates=/usr/share/prometheus/consoles
          command:
            - /bin/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--storage.tsdb.retention.time=4d"  #保存期間
            - "--storage.tsdb.min-block-duration=1h"  #ブロック書き出しタイミング時間
            - "--storage.tsdb.max-block-duration=12h" #
          # args: [
          #   "--config.file=/etc/prometheus/prometheus.yml",
          #   "--storage.tsdb.path=/prometheus",
          #   # "",
          #   # "",
          #   "--web"
          #   ]

          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 400m
              memory: 1600Mi
            requests:
              cpu: 200m
              memory: 800Mi
          volumeMounts:
            - name: config-vol
              mountPath: /etc/prometheus/prometheus.yml
              # mountPath: /prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-vol
              mountPath: /prometheus
      volumes:
        - name: config-vol
          configMap:
            name: prometheus-configmap2
            items:
              - key: prometheus.yml
                path: prometheus.yml
        - name: prometheus-vol
          persistentVolumeClaim:
            claimName: prometheus-pv-claim2
    
