apiVersion: apps/v1
kind: Deployment
metadata:
  name: caliber
  namespace: caliber
spec:
  selector:
    matchLabels:
      app: caliber
  template:
    metadata:
      labels:
        app: caliber
      annotations:
        podinfo: "caliber:Amazonの自炊書籍管理ソフト"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
      containers:
        - name: caliber
          image: lscr.io/linuxserver/calibre:6.12.0
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: caliber-env
          ports:
            - containerPort: 8080
            - containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: /config
            - name: upload
              mountPath: /upload
              readOnly: true
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 1
              memory: 2Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: caliber-pvc-config 
        - name: upload
          persistentVolumeClaim:
            claimName: caliber-pvc-upload 
---
