---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliber-pv-config
spec:
  storageClassName: caliber-config
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: k8s-worker-2
    path: /home/pi/usb/usb1/nfs/kubernetes/caliber-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caliber-pvc-config
  namespace: caliber
spec:
  storageClassName: caliber-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliber-pv-upload
spec:
  storageClassName: caliber-upload
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.0.6
    path: /Booknew/amazon
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caliber-pvc-upload
  namespace: caliber
spec:
  storageClassName: caliber-upload
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi