apiVersion: v1
kind: Service
metadata:
  name: caliber
  namespace: caliber
spec:
  selector:
    app: caliber
  ports:
    - name: caliber-desktop
      port: 8080
      targetPort: 8080
    - name: caliber-web
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caliber
  namespace: caliber
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

spec:
  ingressClassName: nginx
  rules:
  - host: caliber-desk.bookserver.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: caliber
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caliber-web
  namespace: caliber
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: caliber.bookserver.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: caliber
            port:
              number: 8081