apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
      annotations:
        podinfo: "MySQLの確認プログラム"
    spec:
      containers:
      - name: phpmyadmin
        # image: phpmyadmin:5.2.0-fpm
        image: phpmyadmin
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Always
        env:
          - name: TZ
            value: 'Asia/Tokyo'
          - name: PMA_ARBITRARY
            value: "1"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: nextcloud
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  namespace: nextcloud
spec:
  ingressClassName: nginx
  rules:
  - host: phpmyadmin.bookserver.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin
            port:
              number: 80