apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: kavita
spec:
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
      annotations:
        podinfo: "kavita"
    spec:
      containers:
        - name: kavita
          image: kizaing/kavita:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /kavita/config
            - name: manga
              mountPath: /manga
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: kavita-pvc-config 
        - name: manga
          persistentVolumeClaim:
            claimName: kavita-pvc-manga 
---
