version: '3'

services:
  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
        TZ: 'Asia/Tokyo'
    volumes:
        - ./grafana-data:/var/lib/grafana
    ports:
        - 3000:3000
    links:
        - mysql
        - prometheus
#cadvisor-arm
  cadvisor:
    image: braingamer/cadvisor-arm
    volumes: 
        - /:/rootfs:ro
        - /var/run:/var/run:rw 
        - /sys:/sys:ro 
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - 8081:8080
#prometheus
  prometheus:
    image: prom/prometheus
    volumes:
        - "./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
        - 9090:9090
    links:
        - cadvisor
        - golang
        - exporter
#exporter
  exporter:
    image: prom/node-exporter
    # volumes: 
    #  - /home/pi/usb/usb1:/home/pi/usb/usb1
    #  - /home/pi/usb/usb2:/home/pi/usb/usb2
    ports:
      - 9100:9100
  #influxdb
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - ./influxdb:/var/lib/influxdb:rw
    ports:
      - 8086:8086
  #golang
  golang:
    build: services/app
    container_name: golang
    devices:
        - "/dev/i2c-1"
    ports:
        - 9140:9140
