apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-pv-volume"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.24
    path: /home/pi/usb/usb0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi