apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-pv-volume"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/usb/usb1/mariadb
  # nfs:
  #   server: 192.168.0.24
  #   path: /home/pi/usb/usb0/mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
