apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-pv-volume"
  namespace: nextcloud
  labels:
    type: "local"
spec:
  storageClassName: "nextcloud"
  capacity:
    storage: "128Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/usb/usb1/nextcloud2
  # nfs:
    # server: 192.168.0.24
    # path: /home/pi/usb/usb0/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pv-claim
  namespace: nextcloud
spec:
  storageClassName: nextcloud
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
