apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-ssd"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "128Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.24
    path: /home/pi/usb/usb0
