version: '3'

services:
#registry
  registry:
    image: registry:2.7.1
    restart: always
    volumes: 
      - ./regist:/var/lib/registry:rw
    ports: 
      - 5000:5000
#docker-registry-frontend
  front:
    image: ryansmick/arm-docker-registry-frontend:1.0
    restart: always
    environment:
        ENV_DOCKER_REGISTRY_HOST: registry
        ENV_DOCKER_REGISTRY_PORT: 5000
    ports: 
      - 9999:80
    links:
      - registry
