apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-sql-pvc-config
  namespace: piwigo
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-pvc-config
  namespace: piwigo
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-pvc-data
  namespace: piwigo
spec:
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---