# apiVersion: apps/v1
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gf-space
  name: prometheus-configmap2
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
    #external_labels:
    #  monitor: 'codelab-monitor'
      
    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      # - job_name: 'prometheus'
      
      # # Override the global default and scrape targets from this job every 5 seconds.
      #   scrape_interval: 5s
      
      - job_name: 'amedas-pods'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            regex: tenki-exporter
            action: keep
      - job_name: 'kubernetes-pods'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            regex: dockeri2cmoni
            action: keep
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: node_name
    #remote_write:
    #  - url: "http://192.168.0.21:8086/api/v1/prom/write?db=prometheus"
    #    queue_config:
    #      max_shards: 600
    #      max_samples_per_send: 300
    #      batch_send_deadline: 30s
      
    #remote_read:
    #  - url: "http://192.168.0.21:8086/api/v1/prom/read?db=prometheus"
    remote_write:
      - url: "http://192.168.0.6:8086/api/v1/prom/write?db=senser"
      #- url: "http://192.168.0.6:8086/api/v1/prom/write?db=test&u=karosu&p=windam1314"
        queue_config:
          max_shards: 500
          max_samples_per_send: 10000
          batch_send_deadline: 15s
      #- url: "http://35.184.47.193:8086/api/v2/write?org=windam&bucket=prometheus&precision=ns"
      #  bearer_token: Sr--IgqbKT357R3mDaFzQNMLjCpdg1oEuxiKdKVMjXzFIfKLVIxhINjrywZSaplavMH7bzQ_3gZI_XBKOX1lJA==
      # - url: "http://34.67.208.161:8086/api/v1/prom/write?db=prometheus&u=karosuwindam&p=1qaz2wsx3edc"
      #   queue_config:
      #     max_shards: 500
      #     max_samples_per_send: 90000
      #     batch_send_deadline: 30s
      
    remote_read:
     - url: "http://192.168.0.6:8086/api/v1/prom/read?db=senser"
    #  - url: "http://192.168.0.6:8086/api/v1/prom/read?db=test&u=karosu&p=windam1314"

