FROM multiarch/ubuntu-core:armhf-bionic As builder
#RUN apt update && apt upgrade -y
RUN apt update && apt upgrade -y && \
    apt install -y curl gcc git
RUN curl -OL https://dl.google.com/go/go1.14.4.linux-armv6l.tar.gz
RUN tar -C /usr/local -xzf go1.14.4.linux-armv6l.tar.gz
RUN rm -rf go1.14.4.linux-armv6l.tar.gz
ENV PATH $PATH:/usr/local/go/bin
RUN go get -u github.com/seihmd/openbd
RUN go get -u github.com/PuerkitoBio/goquery
RUN go get -u github.com/go-sql-driver/mysql
RUN go get -u github.com/mattn/go-sqlite3
WORKDIR /app
ADD . .
RUN go build -o app
FROM multiarch/ubuntu-core:armhf-bionic
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ./config config
COPY ./html html
COPY ./tmp_html tmp_html
COPY --from=builder /app/app /app
CMD ["./app"]
