version: '3'

services:
#cadvisor-arm
  cadvisor:
    image: braingamer/cadvisor-arm
    restart: always
    volumes: 
        - /:/rootfs:ro
        - /var/run:/var/run:rw 
        - /sys:/sys:ro 
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - 8081:8080
#exporter
  exporter:
    image: prom/node-exporter
    restart: always
    volumes: 
     - /home/pi/usb/usb1:/home/pi/usb/usb1
     - /home/pi/usb/usb2:/home/pi/usb/usb2
    ports:
      - 9100:9100
